name: Build

on:
  push:

  schedule:
    - cron: '31 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        with:
          arguments: |
            build
      - name: Dependency check
        uses: gradle/gradle-build-action@v3
        with:
          arguments: |
            dependencyCheckAnalyze
      - name: Upload Test results
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: Dependency check report
          path: ${{github.workspace}}/build/reports
      - name: Process Gradle dependencies
        uses: mikepenz/gradle-dependency-submission@v1.0.0
